[project]
name = "safrs"

version = "3.2.0"

description="SAFRS : SqlAlchemy Flask-Restful Swagger"

readme = "README.md"

requires-python = ">=3.10"

license = {file = "LICENSE"}

keywords=["SqlAlchemy", "Flask", "REST", "Swagger", "JsonAPI", "OpenAPI"]

authors = [
  {name = "Thomas Pollet", email = "thomas.pollet@gmail.com" }
]

classifiers = [  # Optional
  # How mature is this project? Common values are
  #   3 - Alpha
  #   4 - Beta
  #   5 - Production/Stable
  "Development Status :: 3 - Alpha",

  # Indicate who your project is intended for
  "Intended Audience :: Developers",
  "Topic :: Software Development :: Libraries",
  "Framework :: Flask",
  "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3 :: Only",
]

dependencies = [ "Flask>=3.1.3", "Flask-SQLAlchemy>=3.1.1", "PyYAML>=6.0.3", "SQLAlchemy>=2.0.48", "Flask-RESTful>=0.3.10", "flask-restful-swagger-2>=0.35", "flask-swagger-ui>=5.21.0", "Flask-Cors>=6.0.2", "fastapi[standard]>=0.135.1" ]

[project.optional-dependencies] # Optional
flask = ["Flask-RESTful>=0.3.10", "flask-restful-swagger-2>=0.35", "flask-swagger-ui>=5.21.0", "Flask-Cors>=6.0.2"]
fastapi = ["fastapi[standard]>=0.135.1"]
all = ["Flask-RESTful>=0.3.10", "flask-restful-swagger-2>=0.35", "flask-swagger-ui>=5.21.0", "Flask-Cors>=6.0.2", "fastapi[standard]>=0.135.1"]
dev = ["Flask-RESTful>=0.3.10", "flask-restful-swagger-2>=0.35", "flask-swagger-ui>=5.21.0", "Flask-Cors>=6.0.2", "fastapi[standard]>=0.135.1"]
test = ["Flask-RESTful>=0.3.10", "flask-restful-swagger-2>=0.35", "flask-swagger-ui>=5.21.0", "Flask-Cors>=6.0.2", "fastapi[standard]>=0.135.1"]

[project.urls]  # Optional
"Homepage" = "https://github.com/thomaxxl/safrs"

[tool.setuptools]
package-data = {}

[build-system]
requires = ["setuptools>=43.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.mypy]
ignore_missing_imports = true
exclude = '(^|/)(docs|examples|tests)/'
