# coding: utf-8

"""
    SAFRS Demo App

    <a href=http://jsonapi.org>Json-API</a> compliant API built with https://github.com/thomaxxl/safrs <br/>- <a href=\"https://github.com/thomaxxl/safrs/blob/master/examples/demo_relationship.py\">Source code of this page</a> <br/> - Auto-generated swagger spec: <a href=swagger.json>swagger.json</a> <br/> - Petstore <a href=http://petstore.swagger.io/?url=http://thomaxxl.pythonanywhere.com/api/swagger.json>Swagger2 UI</a>                                         # noqa: E501

    OpenAPI spec version: 0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from setuptools import setup, find_packages  # noqa: H301

NAME = "swagger-client"
VERSION = "1.0.0"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = ["urllib3 >= 1.15", "six >= 1.10", "certifi", "python-dateutil"]

setup(
    name=NAME,
    version=VERSION,
    description="SAFRS Demo App",
    author_email="",
    url="",
    keywords=["Swagger", "SAFRS Demo App"],
    install_requires=REQUIRES,
    packages=find_packages(),
    include_package_data=True,
    long_description="""\
    &lt;a href&#x3D;http://jsonapi.org&gt;Json-API&lt;/a&gt; compliant API built with https://github.com/thomaxxl/safrs &lt;br/&gt;- &lt;a href&#x3D;\&quot;https://github.com/thomaxxl/safrs/blob/master/examples/demo_relationship.py\&quot;&gt;Source code of this page&lt;/a&gt; &lt;br/&gt; - Auto-generated swagger spec: &lt;a href&#x3D;swagger.json&gt;swagger.json&lt;/a&gt; &lt;br/&gt; - Petstore &lt;a href&#x3D;http://petstore.swagger.io/?url&#x3D;http://thomaxxl.pythonanywhere.com/api/swagger.json&gt;Swagger2 UI&lt;/a&gt;                                         # noqa: E501
    """,
)
