# coding: utf-8

"""
    SAFRS Demo Application

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.user_lookup import UserLookup  # noqa: E501
from swagger_client.rest import ApiException


class TestUserLookup(unittest.TestCase):
    """UserLookup unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserLookup(self):
        """Test UserLookup"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.user_lookup.UserLookup()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
