# coding: utf-8

"""
    SAFRS Demo App

    <a href=http://jsonapi.org>Json-API</a> compliant API built with https://github.com/thomaxxl/safrs <br/>- <a href=\"https://github.com/thomaxxl/safrs/blob/master/examples/demo_relationship.py\">Source code of this page</a> <br/> - Auto-generated swagger spec: <a href=swagger.json>swagger.json</a> <br/> - Petstore <a href=http://petstore.swagger.io/?url=http://thomaxxl.pythonanywhere.com/api/swagger.json>Swagger2 UI</a>                                         # noqa: E501

    OpenAPI spec version: 0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.books_api import BooksApi  # noqa: E501
from swagger_client.rest import ApiException


class TestBooksApi(unittest.TestCase):
    """BooksApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.books_api.BooksApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_2(self):
        """Test case for 2

        Update a Book object              # noqa: E501
        """
        pass

    def test_3(self):
        """Test case for 3

        Delete a Book object              # noqa: E501
        """
        pass

    def test_4(self):
        """Test case for 4

        Delete from Book user  # noqa: E501
        """
        pass

    def test_5(self):
        """Test case for 5

        Retrieve a Book object              # noqa: E501
        """
        pass

    def test_5_0(self):
        """Test case for 5_0

        Create a Book object              # noqa: E501
        """
        pass

    def test_6(self):
        """Test case for 6

        Retrieve a Book object                          # noqa: E501
        """
        pass

    def test_6_0(self):
        """Test case for 6_0

        Create a Book object                          # noqa: E501
        """
        pass

    def test_7(self):
        """Test case for 7

        Retrieve a user object  # noqa: E501
        """
        pass

    def test_7_0(self):
        """Test case for 7_0

        Update user  # noqa: E501
        """
        pass

    def test_8(self):
        """Test case for 8

        Invoke Book.get_list              # noqa: E501
        """
        pass

    def test_8_0(self):
        """Test case for 8_0

        Retrieve a user object  # noqa: E501
        """
        pass


if __name__ == "__main__":
    unittest.main()
