# coding: utf-8

"""
    SAFRS Demo Application

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.user_post_sample1 import UserPOSTSample1  # noqa: E501
from swagger_client.rest import ApiException


class TestUserPOSTSample1(unittest.TestCase):
    """UserPOSTSample1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserPOSTSample1(self):
        """Test UserPOSTSample1"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.user_post_sample1.UserPOSTSample1()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
