# coding: utf-8

"""
    SAFRS Demo Application

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.user_post_sample import UserPOSTSample  # noqa: E501
from swagger_client.rest import ApiException


class TestUserPOSTSample(unittest.TestCase):
    """UserPOSTSample unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserPOSTSample(self):
        """Test UserPOSTSample"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.user_post_sample.UserPOSTSample()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
