# coding: utf-8

"""
    SAFRS Demo Application

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.books_api import BooksApi  # noqa: E501
from swagger_client.rest import ApiException


class TestBooksApi(unittest.TestCase):
    """BooksApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.books_api.BooksApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_booksstring_book_id_ad0d(self):
        """Test case for delete_booksstring_book_id_ad0d

        Delete a Book object              # noqa: E501
        """
        pass

    def test_delete_booksstring_book_id_userstring_user_id25ae(self):
        """Test case for delete_booksstring_book_id_userstring_user_id25ae

        Delete from Book user  # noqa: E501
        """
        pass

    def test_get_books49c2(self):
        """Test case for get_books49c2

        Retrieve a Book object              # noqa: E501
        """
        pass

    def test_get_booksstring_book_id5596(self):
        """Test case for get_booksstring_book_id5596

        Retrieve a Book object                          # noqa: E501
        """
        pass

    def test_get_booksstring_book_id_userfe6e(self):
        """Test case for get_booksstring_book_id_userfe6e

        Retrieve a user object  # noqa: E501
        """
        pass

    def test_get_booksstring_book_id_userstring_user_idecbd(self):
        """Test case for get_booksstring_book_id_userstring_user_idecbd

        Retrieve a user object  # noqa: E501
        """
        pass

    def test_patch_booksstring_book_id_b128(self):
        """Test case for patch_booksstring_book_id_b128

        Update a Book object              # noqa: E501
        """
        pass

    def test_post_books_dbb6(self):
        """Test case for post_books_dbb6

        Create a Book object              # noqa: E501
        """
        pass

    def test_post_books_get_list7301(self):
        """Test case for post_books_get_list7301

        Invoke Book.get_list              # noqa: E501
        """
        pass

    def test_post_books_lookup0981(self):
        """Test case for post_books_lookup0981

        Invoke Book.lookup              # noqa: E501
        """
        pass

    def test_post_booksstring_book_id1dee(self):
        """Test case for post_booksstring_book_id1dee

        Create a Book object                          # noqa: E501
        """
        pass

    def test_post_booksstring_book_id_user0e8a(self):
        """Test case for post_booksstring_book_id_user0e8a

        Update user  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
