# coding: utf-8

"""
    SAFRS Demo App

    <a href=http://jsonapi.org>Json-API</a> compliant API built with https://github.com/thomaxxl/safrs <br/>- <a href=\"https://github.com/thomaxxl/safrs/blob/master/examples/demo_relationship.py\">Source code of this page</a> <br/> - Auto-generated swagger spec: <a href=swagger.json>swagger.json</a> <br/> - Petstore <a href=http://petstore.swagger.io/?url=http://thomaxxl.pythonanywhere.com/api/swagger.json>Swagger2 UI</a>                                         # noqa: E501

    OpenAPI spec version: 0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.post_book_get_list import PostBookGetList  # noqa: E501
from swagger_client.rest import ApiException


class TestPostBookGetList(unittest.TestCase):
    """PostBookGetList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPostBookGetList(self):
        """Test PostBookGetList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.post_book_get_list.PostBookGetList()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
