# coding: utf-8

# flake8: noqa
"""
    SAFRS Demo Application

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from swagger_client.models.book_get_list import BookGetList
from swagger_client.models.book_post_sample import BookPOSTSample
from swagger_client.models.book_post_sample1 import BookPOSTSample1
from swagger_client.models.books_relationship import BooksRelationship
from swagger_client.models.post_book_get_list import PostBookGetList
from swagger_client.models.post_user_get_list import PostUserGetList
from swagger_client.models.post_user_send_mail import PostUserSendMail
from swagger_client.models.user_get_list import UserGetList
from swagger_client.models.user_post_sample import UserPOSTSample
from swagger_client.models.user_post_sample1 import UserPOSTSample1
from swagger_client.models.user_relationship import UserRelationship
from swagger_client.models.user_send_mail import UserSendMail
