# coding: utf-8

# flake8: noqa
"""
    SAFRS Demo App

    <a href=http://jsonapi.org>Json-API</a> compliant API built with https://github.com/thomaxxl/safrs <br/>- <a href=\"https://github.com/thomaxxl/safrs/blob/master/examples/demo_relationship.py\">Source code of this page</a> <br/> - Auto-generated swagger spec: <a href=swagger.json>swagger.json</a> <br/> - Petstore <a href=http://petstore.swagger.io/?url=http://thomaxxl.pythonanywhere.com/api/swagger.json>Swagger2 UI</a>                                         # noqa: E501

    OpenAPI spec version: 0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from swagger_client.models.book_get_list import BookGetList
from swagger_client.models.book_post_sample import BookPOSTSample
from swagger_client.models.book_post_sample1 import BookPOSTSample1
from swagger_client.models.books_relationship import BooksRelationship
from swagger_client.models.post_book_get_list import PostBookGetList
from swagger_client.models.post_user_get_list import PostUserGetList
from swagger_client.models.user_get_list import UserGetList
from swagger_client.models.user_post_sample import UserPOSTSample
from swagger_client.models.user_post_sample1 import UserPOSTSample1
from swagger_client.models.user_relationship import UserRelationship
